/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View = Laya.View;
var Scene = Laya.Scene;
var REG = Laya.ClassUtils.regClass;
export var ui;
(function (ui) {
    var test;
    (function (test) {
        class BackpackUI extends View {
            constructor() {
                super();
            }
            createChildren() {
                super.createChildren();
                this.createView(BackpackUI.uiView);
            }
        }
        BackpackUI.uiView = { "type": "View", "props": { "width": 640, "height": 300 }, "loadList": [], "loadList3D": [] };
        test.BackpackUI = BackpackUI;
        REG("ui.test.BackpackUI", BackpackUI);
        class RolePanelUI extends View {
            constructor() {
                super();
            }
            createChildren() {
                super.createChildren();
                this.createView(RolePanelUI.uiView);
            }
        }
        RolePanelUI.uiView = { "type": "View", "props": { "width": 640, "height": 300 }, "compId": 2, "child": [{ "type": "Sprite", "props": { "y": 71, "x": 98, "width": 511, "var": "sprite", "texture": "test/b1.png", "height": 28 }, "compId": 3 }], "loadList": ["test/b1.png"], "loadList3D": [] };
        test.RolePanelUI = RolePanelUI;
        REG("ui.test.RolePanelUI", RolePanelUI);
        class TestSceneUI extends Scene {
            constructor() { super(); }
            createChildren() {
                super.createChildren();
                this.loadScene("test/TestScene");
            }
        }
        test.TestSceneUI = TestSceneUI;
        REG("ui.test.TestSceneUI", TestSceneUI);
    })(test = ui.test || (ui.test = {}));
})(ui || (ui = {}));
//# sourceMappingURL=layaMaxUI.js.map